
pipeline {
    agent any

    stages {
        stage('build package') {
            environment {
                JAVA_HOME = 'C:/java/tools/jdk-21.0.2'
            }
            steps {
                bat 'echo executando build package'
                bat 'mvn -version'
                bat 'mvn clean package'
            }
        }
    }

}
